### ISSUE TITLE
Problem with Building ... 

### ISSUE THREAD

**Issue by siftmash** [vardius/web-components-webpack-es6-boilerplate#1]
You forgot about many dependencies
npm install --save-dev  electron-to-chromium
npm install --save-dev babel-plugin-transform-es2015-function-name
npm install --save-dev babel-plugin-transform-es2015-shorthand-properties
npm install --save-dev babel-plugin-transform-es2015-destructuring
npm install --save-dev babel-plugin-syntax-object-rest-spread

**Comment by vardius** [comment]
doesn't babel env handle this ?

**Comment by siftmash** [comment]
I don't know. I had to install it to run your project

**Comment by vardius** [comment]
es2015 should be included, rest-spread need to be added as it is stage0
